server:
  port: 8081
  servlet:
    context-path: /provider
spring:
  application:
    name: springcloud-provider
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://127.0.0.1:3306/local_db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&allowPublicKeyRetrieval=true
    username: root
    password: 335335
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 127.0.0.1
    port: 6379
    password: 335335
    jedis:
      pool:
        max-active: 8
  main:
    allow-bean-definition-overriding: true
logging:
  config: classpath:config/logback.xml
token:
  #token设置三天过期
  expire-time: 259200000
  #redis设置两小时未操作过期
  no-operation-time: 7200000
  secret-key: hfD1DF123jDjdf3uitqwe63GreKKS2wwt25keauiOPdM


